In [1]:
import numpy as np

In [2]:
lst1 = list(range(1,11))

In [3]:
lst1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
arr1 = np.array(lst1)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
type(lst1)

list

In [7]:
arr1.shape

(10,)

In [8]:
lst2 = list(range(1,11))
lst2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
arr2 = np.array(lst2)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr3 = np.array([lst1, lst2])
arr3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [11]:
arr3 = np.array([arr1, arr2])
arr3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [12]:
arr3.shape

(2, 10)

In [13]:
arr3.ndim

2

In [14]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
multi_array = np.array(my_matrix)
multi_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
multi_array.shape

(3, 3)

In [17]:
multi_array.ndim

2

In [18]:
my_matrix = [[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]]
my_matrix

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [19]:
multi_array = np.array(my_matrix)
multi_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
multi_array.shape

(2, 3, 3)

In [21]:
multi_array.ndim

3

### Reshape

In [22]:
array1 = np.array([1,2,3,4,5,6])
array1

array([1, 2, 3, 4, 5, 6])

In [23]:
array1 = array1.reshape(3,2)
array1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
array1.ndim

2

### aRange

In [25]:
arr_seq = np.arange(1,11)
arr_seq

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr_seq = np.arange(1,11,2) # Step size can also be given similar to list
arr_seq

array([1, 3, 5, 7, 9])

In [27]:
arr_seq = np.arange(1,11)
arr_seq

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr = np.random.randint(10,20,10)
arr

array([14, 14, 15, 11, 19, 14, 14, 12, 16, 12])

In [29]:
arr_seq = np.arange(1,11,2)
arr_seq

array([1, 3, 5, 7, 9])

In [30]:
arr_seq[::-1]

array([9, 7, 5, 3, 1])

In [31]:
arr_seq[0] = 20

In [32]:
arr_seq

array([20,  3,  5,  7,  9])

In [33]:
arr_seq[:3]

array([20,  3,  5])

In [34]:
arr_seq[:3] = 20

In [35]:
arr_seq

array([20, 20, 20,  7,  9])

In [36]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [37]:
y = np.array([[5,6],[7,8]])
y

array([[5, 6],
       [7, 8]])

In [38]:
x + y

array([[ 6,  8],
       [10, 12]])

In [39]:
x - y

array([[-4, -4],
       [-4, -4]])

In [40]:
x * y

array([[ 5, 12],
       [21, 32]])

In [41]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [42]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [43]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [44]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [45]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [46]:
np.sum(x)

10

In [47]:
np.sum(x, axis=1)

array([3, 7])

In [48]:
np.sum(x, axis=0)

array([4, 6])

In [49]:
np.min(x)

1

In [50]:
np.max(x)

4

In [51]:
np.cumsum(x)

array([ 1,  3,  6, 10])

In [52]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [53]:
x.T

array([[1, 3],
       [2, 4]])